version: "3.7"
services:
    redis-service:
        image: "redis:4.0.11-alpine"
        container_name: redis-service
        command: "redis-server --requirepass 123456"
        ports:
            - "6379:6379"
        restart: unless-stopped

    postgres-service:
        image: "postgres:10.5-alpine"
        container_name: postgres-service
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: "123456"
            POSTGRES_DB: airflow
        ports:
            - "5432:5432"
        restart: unless-stopped
    
    mongo-service:
        image: "mongo:4.4.5-bionic"
        container_name: mongo-service
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_DATABASE=test
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes:
            # seeding scripts
            - ./scripts:/docker-entrypoint-initdb.d
        restart: unless-stopped

    neo4j-serivce:
        image: neo4j:4.2.6
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - ./conf:/conf
            - ./data:/data
            - ./import:/import
            - ./logs:/logs
            - ./plugins:/plugins
        environment: 
            # Raise memory limits
            - NEO4J_dbms_memory_pagecache_size=1G
            - NEO4J_dbms.memory.heap.initial_size=1G
            - NEO4J_dbms_memory_heap_max__size=1G
    firebase-service:
        image: firebase-service:latest
        container_name: firebase-service
        build:
            context: .
            dockerfile: Dockerfile-firebase
        restart: always